name: Library test, lint and typecheck

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        curl -sSL https://pdm.fming.dev/install-pdm.py | python3 -
        pdm install
    - name: Lint with Ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pdm run lint
    - name: Test with pytest
      run: |
        pdm run test
    - name: Typecheck with mypy
      run: |
        pdm run typecheck
